### ISSUE TITLE
Cannot enable ui with vault 0.10.x

### ISSUE THREAD

**Issue by giorgian** [sous-chefs/vault#114]
The `vault_config` resource does not accept `ui true`.

**Comment by giorgian** [comment]
More generally, whitelisting attributes means that the cookbook must be edited every time there's a change in the vault configuration syntax; maybe having some "other_options" hash would allow users to quickly adapt to syntax changes in the config file?

**Comment by PowerSchill** [comment]
This functionality was implemented with #115.
