### ISSUE TITLE
Release a version with support for > 0.6.5

### ISSUE THREAD

**Issue by dbresson** [sous-chefs/vault#117]
It looks like support has been in master for a while now. Please create a release.

**Comment by Lasering** [comment]
Is there any way I can help to make the release in the supermarket happen? @josephholsten @damacus

**Comment by fortman** [comment]
Wow, latest release 2.5 from "Jan 20, 2017".  Right now my best option is to clone this repo as a local repo until we get a tag with latest functionality.  Yikes.  Or roll my own cookbook, but why when this should have a recent tag.

**Comment by josephholsten** [comment]
@Lasering @fortman I'm sorry for not getting back to you about this. Some of us are having an office hours event on thursday 2019-02-14 at 10am pacific, I'd love if you dropped by [chat](https://community-slack.chef.io/) before then and helped us get this out the door.

**Comment by PowerSchill** [comment]
Just released version 3.0.0 of the cookbook. However, we already have plans for 4.0.0 so we would love to have your help with the next version.

**Comment by Lasering** [comment]
Sorry for the late response. I can help with the 4.0.0 release.
