### ISSUE TITLE
Can we get a new release?

### ISSUE THREAD

**Issue by Rytis-Lebedys** [sous-chefs/vault#133]
Hello, I see that support for user interface configuration is in the master for a while now. Could you release it so we could use this feature?

**Comment by josephholsten** [comment]
I'd like that, but our tests aren't currently passing (see #135). As I don't use this cookbook myself, I don't have another way of knowing it's not terribly broken.

I might understand if you tell me the right answer is to remove the tests, but I'd like at least a second opinion before I go ripping things out myself.

**Comment by Rytis-Lebedys** [comment]
I see that tests are passing now. Can we expect a new release any time soon?

**Comment by josephholsten** [comment]
I'm sorry, we have a meta ticket for improving this: https://github.com/sous-chefs/meta/issues/89

so @damacus: help!

**Comment by Rytis-Lebedys** [comment]
Any news?

**Comment by PowerSchill** [comment]
I will see if I can get a release done this week (Sunday by the latest depending on competing priorities). Have you or anyone else done any kind of testing with the current repo version? I have a slightly older version that I am using in production but haven't been able to do *this* version yet.

**Comment by Rytis-Lebedys** [comment]
Thank you. We are using 2.5.0 in production.

**Comment by Rytis-Lebedys** [comment]
Thanks for the release. Are you going to upload it to the supermarket?

**Comment by PowerSchill** [comment]
Working through a few logistical changes with @damacus  but we will get it released to the supermarket.

**Comment by PowerSchill** [comment]
Version 3.0.0 has been released to the Supermarket!
