### ISSUE TITLE
vault_secret resource missing

### ISSUE THREAD

**Issue by shoekstra** [sous-chefs/vault#162]
Hi!

Please restore the `vault_secret` resource, it's needed to read secrets from Vault using Chef. 

Looks like it went missing in [this PR](https://github.com/sous-chefs/vault/pull/153).

Thanks in advance,

Stephen

**Comment by PowerSchill** [comment]
Was taking a look at this and what I am not personally sure is whether using the `node.run_state` is still the correct method. Currently in my environment I have a library that is part of a cookbook that provides a function that is utilized.

**Comment by shoekstra** [comment]
Hey @PowerSchill, thanks for taking the time to check this out!

Using `node.run_state` is still the recommended way as far as I know ([according to the docs anyway](https://docs.chef.io/recipes.html#node-run-state)) to store transient data that will not be persisted and saved to the Chef server.

Take this example:

```ruby
vault_secret "secret/#{node['hostname']}/ssh_host_keys" do
  address node['vault']['address']
  token File.open(node['vault']['token_path'], 'rb').read.chomp
end

%w(
  ssh_host_dsa_key
  ssh_host_dsa_key.pub
  ...
).each do |ssh_host_key|
  file "/etc/ssh/#{ssh_host_key}" do
    ...
    sensitive true
    content lazy { node.run_state["secret/#{node['hostname']}/ssh_host_keys"].data[:"#{ssh_host_key}"] }
    notifies :restart, 'service[sshd]', :delayed
  end
end
```

Doing this allows me to retrieve values from Vault and store them in a hash in the node object to be used by other resources, safe in the knowledge that that part of the node object will not be saved to the Chef server and thus those secrets are only in memory while the Chef client runs.

Just to clarify, this issue is around the functionality that used to exist, not how it was implemented or could be reimplemented. I'm totally not opposed to implementing this in a better way, but I hope this information will help in restoring what was removed until that happens.

Stephen

**Comment by PowerSchill** [comment]
I will work on it but we definitely have to remove the Poise dependency.  If you are aware of an easy way we can start a vault server and populate some values that would be awesome so I can include the unit test.
