### ISSUE TITLE
Vault service running but not listening on port 8200

### ISSUE THREAD

**Issue by oscarmorasu** [sous-chefs/vault#182]
### :speaking_head: Foreword

I need to upgrade from Vault 0.9.6 -> 1.34. I am using an old version of this cook book (one with recipe/libraries). I want to upgrade my recipe to use the latest version of this cook book (4.0.1), which is resources based.

## :person_frowning: Problem Statement

I created a recipe `new.rb` with this content:

``` ruby
hashicorp_vault_install 'package' do
    ui true
    disable_performance_standby true
    tls_disable true
    sensitive true
    version '1.3.4'
    action [:install]
  end
```
This is the `kitchen.yml`:

``` yml
---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  product_name: chef

platforms:
  - name: ubuntu-16.04

suites:
  - name: new
    run_list:
      - test-vault::new
```

And the test file `default_spec.rb`

``` ruby
describe 'test-vault::default' do
  describe service('vault') do
    it { should be_running }
    it { should be_enabled }
  end

  describe file('/etc/vault/vault.json') do
    it { should be_file }
    it { should be_mode 640 }
    it { should be_owned_by 'vault' }
    it { should be_grouped_into 'vault' }
  end

  describe command('VAULT_ADDR=http://127.0.0.1:8200 vault status') do
    its(:stdout) { should match /Version[ ]+1.3.4/ }
  end

end
```
When I run `kitchen test new-ubuntu-16.04`

The last test fails.

I went into the Virtualbox and checked the service is running:`systemctl status vault`:

```
● vault.service - Runs Hashicorp Vault
   Loaded: loaded (/etc/systemd/system/vault.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2020-04-02 02:00:15 UTC; 16min ago
 Main PID: 12735 (vault)
    Tasks: 9
   Memory: 6.5M
      CPU: 358ms
   CGroup: /system.slice/vault.service
           └─12735 /usr/local/bin/vault server -config=/etc/vault/vault.json -log-level=info
```

Then I checked for any errors: `journalctl -u vault`

```
Apr 02 02:00:15 new-ubuntu-1604 systemd[1]: Started Runs Hashicorp Vault.
Apr 02 02:00:16 new-ubuntu-1604 vault[12735]: WARNING! Unable to read storage migration status.
Apr 02 02:00:16 new-ubuntu-1604 vault[12735]: 2020-04-02T02:00:16.031Z [INFO]  proxy environment: http_proxy= https_proxy= no_proxy=
Apr 02 02:00:16 new-ubuntu-1604 vault[12735]: 2020-04-02T02:00:16.031Z [WARN]  storage migration check error: error="open /mnt/vault/data/core/_migration: permission denied"
```

I don't think the permission denied is a problem since Vault is still sealed.

I ran the same command as the test `VAULT_ADDR=http://127.0.0.1:8200 vault status`

```
Error checking seal status: Get http://127.0.0.1:8200/v1/sys/seal-status: dial tcp 127.0.0.1:8200: connect: connection refused
```

According to these observations Vault service is running, there were no errors starting, but it's not listening on port 8200.

What am I missing?

Any help is much appreciated.

**Comment by steve-yc** [comment]
Any updates on this one?  I'm having the same issue on an "out of the box" install

hashicorp_vault_install 'testing' do
  ui true
  disable_performance_standby true
  tls_disable true
  sensitive true
  action [:install]
end

**Comment by steve-yc** [comment]
BTW, this also happens with your image: ` server-install-ubuntu-1804`

```Nov 10 14:36:32 vagrant vault[13420]: 2020-11-10T14:36:32.068Z [WARN]  storage migration check error: error="open /mnt/vault/data/core/_migration: permission denied"
Nov 10 14:36:34 vagrant vault[13420]: 2020-11-10T14:36:34.069Z [WARN]  storage migration check error: error="open /mnt/vault/data/core/_migration: permission denied"
Nov 10 14:36:36 vagrant vault[13420]: 2020-11-10T14:36:36.071Z [WARN]  storage migration check error: error="open /mnt/vault/data/core/_migration: permission denied"
Nov 10 14:36:38 vagrant vault[13420]: 2020-11-10T14:36:38.073Z [WARN]  storage migration check error: error="open /mnt/vault/data/core/_migration: permission denied"
Nov 10 14:36:40 vagrant vault[13420]: 2020-11-10T14:36:40.074Z [WARN]  storage migration check error: error="open /mnt/vault/data/core/_migration: permission denied"
Nov 10 14:36:42 vagrant vault[13420]: 2020-11-10T14:36:42.076Z [WARN]  storage migration check error: error="open /mnt/vault/data/core/_migration: permission denied"```

**Comment by kurtbomya** [comment]
I'm getting the same error message as @steve-yc immediately above. 🤔

**Comment by ramereth** [comment]
If anyone has time to make a PR which addresses, please free to do so and we'll review/merge it!

**Comment by bmhughes** [comment]
As of version 5 the install resource is no longer an all-in-one resource so you will need to call one of the config resources to generate the vault configuration and the service resource to generate and control the service. Without these you will be running a default configuration with depending on the install method used may not even exist.

The [UPGRADING.md](https://github.com/sous-chefs/vault/blob/master/UPGRADING.md) file covers the breaking changes.

**Comment by bmhughes** [comment]
Closing this out for the time being as it's been over a year since it was opened.
