### ISSUE TITLE
Allow tuning LimitNOFILE in systemd unit

### ISSUE THREAD

**Issue by pierresouchay** [sous-chefs/vault#190]
systemd unit does not seem to allow tuning LimitNOFILE, would it be possible to add support to tune it?

**Comment by JohnRoesler** [comment]
Yes! The systemd unit could made a property on the service resource and you could tune any element of it. 

Fancy making a PR?

**Comment by pierresouchay** [comment]
@JohnRoesler done, made a PR

**Comment by JohnRoesler** [comment]
Merged. Well try and get this released soon
