### ISSUE TITLE
name is a required property

### ISSUE THREAD

**Issue by B1tem3250** [sous-chefs/vault#192]
Hi,

I am getting a `Chef::Exceptions::ValidationFailed: name is a required property` error when running kitchen tests.

I created a wrapper cookbook and added the below to `recipes/default.rb`

```ruby
hashicorp_vault_install 'package' do
  cluster_name 'vault_dev'
  ui true
  version '1.4.0'
  disable_performance_standby true
  require 'pry'; binding.pry
  sensitive true
end
```

I have added the above as per the `Usage` section from the `README`.
I have used an earlier version of chef client and the latest and still get the same error.
I have used `pry` to debug when running `kitchen login` and see that the name value is set to `package`.

Is there something I am missing or doing wrong?

Any help is much appreciated.

**Comment by damacus** [comment]
Hi @B1tem3250, 

thanks for filling an issue, can you reopen this issue using the template. As we have an incomplete picture of what platform you're running on, which version of Chef you're using. This is all in the standard `BUG` template. 

Thanks!

**Comment by B1tem3250** [comment]
Hi @damacus,

Sorry about that wasn't sure it would be raised as a bug.
Will do so.

Thanks for getting back to me.

**Comment by knightorc** [comment]
@B1tem3250 @B1tem3250 
I hit the same issue.  chicken-n-egg.  it is the tls cert resource that is complaining.

In testing my upgrade path from the 3.1.x gen of the cookbook to this 4.0.x version, in testing adding `tls_disable true`
processed. 

when using default tls_disable false

you need to provide the following attributes.

tls_cert_file
tls_key_file

**Comment by B1tem3250** [comment]
@knightorc 
Thanks for the assistance, I have tried as per your comment above and all seems to be working 100%.
Thanks once again, much appreciated.
