### ISSUE TITLE
Vault install resource should pass log_level to hashicorp_vault_service

### ISSUE THREAD

**Issue by Lasering** [sous-chefs/vault#208]
## :person_frowning: Problem Statement

Setting log_level in vault config is always overridden by the log level set in the vault service.

## :grey_question: Possible Solution

The install resource should pass log_level to the service resource.

**Comment by bmhughes** [comment]
Unless the user provides their own `systemd_unit_content` to to the service resource as far as I know we don't set the log level, also this would create an inter-dependency between resources which is not ideal to say the least.

Do you have an example set of resources where this is a problem?

**Comment by Lasering** [comment]
It seems in the new version of the cookbook this problem no longer exists.
